# Generated by Django 3.1.1 on 2020-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='svg',
            field=models.FileField(upload_to='about'),
        ),
        migrations.AlterField(
            model_name='service',
            name='svg',
            field=models.FileField(upload_to='about'),
        ),
    ]
