# Generated by Django 3.1.1 on 2020-10-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201010_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about'),
        ),
    ]
