# Generated by Django 3.1.1 on 2020-10-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_realtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='position',
            field=models.CharField(blank=True, choices=[('about', 'about'), ('contact', 'contact')], max_length=20, null=True),
        ),
    ]
