# Generated by Django 3.1.1 on 2020-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('address', 'address'), ('phone', 'phone'), ('email', 'email')], max_length=100, unique=True),
        ),
    ]
