# Generated by Django 3.1.1 on 2020-09-29 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('H', 'Home'), ('G', 'Garage'), ('F', 'Flat')], max_length=40)),
                ('sq_ft', models.IntegerField()),
                ('baths', models.IntegerField(blank=True)),
                ('beds', models.IntegerField(blank=True)),
                ('garages', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('features', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='home')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
