# Generated by Django 3.1.1 on 2020-09-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200929_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='rent_or_sale',
            field=models.CharField(choices=[('R', 'For rent'), ('S', 'For sale')], default='For sale', max_length=10),
            preserve_default=False,
        ),
    ]
