# Generated by Django 3.1.1 on 2020-09-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_home_rent_or_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rent_or_sale',
            field=models.CharField(choices=[('For rent', 'For rent'), ('For sale', 'For sale')], max_length=10),
        ),
    ]
