# Generated by Django 3.1.1 on 2020-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200929_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='type',
            field=models.CharField(choices=[('Home', 'Home'), ('Garage', 'Garage'), ('Flat', 'Flat')], max_length=40),
        ),
    ]
