# Generated by Django 3.1.1 on 2020-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200929_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
