# Generated by Django 3.1.1 on 2020-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200930_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
