# Generated by Django 3.1.1 on 2020-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20201004_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='home',
            name='featured_properties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='hot_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='home',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
