# Generated by Django 3.1.1 on 2020-10-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20201008_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
